name: Submit stable release to WinGet

on:
  workflow_dispatch:
  release:
    types: [released]

jobs:

  winget:
    name: Publish release to WinGet
    runs-on: windows-latest
    steps:
      - name: Submit installer to Windows Package Manager Community Repository
        run: |
          $github = Get-Content "${{ github.event_path }}"" | ConvertFrom-Json
          $installerUrl = $github.release.assets | Where-Object -Property name -match "EverythingToolbar*.msi" | Select -ExpandProperty browser_download_url -First 1
          iwr https://aka.ms/wingetcreate/latest -OutFile wingetcreate.exe
          .\wingetcreate.exe update stnkl.EverythingToolbar -s -v $github.release.tag_name -u $installerUrl -t ${{ secrets.WINGET_PAT }}
